import React, { useEffect, useMemo, useRef, useState } from 'react';
import axios from 'axios';
import { motion } from 'framer-motion';
import { Breadcrumb } from '../components/shared/PageElements';

const emptyPerson = { name: '', dob: '', hour: '', minute: '', meridiem: 'AM', place: '' };
const kootas = ['Varna', 'Vashya', 'Tara', 'Yoni', 'Graha Maitri', 'Gana', 'Bhakoot', 'Nadi'];

function asText(value) {
  if (value === null || value === undefined) return '';
  if (typeof value === 'object') return value.description || value.message || value.name || '';
  return String(value);
}

function PlaceInput({ value, onChange, label }) {
  const [items, setItems] = useState([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [active, setActive] = useState(-1);
  const ref = useRef(null);
  useEffect(() => { const close = (e) => !ref.current?.contains(e.target) && setOpen(false); document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  useEffect(() => { if (value.trim().length < 2) { setItems([]); return undefined; } const c = new AbortController(); const id = setTimeout(async () => { try { setLoading(true); const { data } = await axios.get('/api/astrology/places', { params: { q: value }, signal: c.signal }); setItems(data); setOpen(true); } catch { if (!c.signal.aborted) { setItems([]); setOpen(true); } } finally { if (!c.signal.aborted) setLoading(false); } }, 300); return () => { clearTimeout(id); c.abort(); }; }, [value]);
  const select = (item) => { onChange(item.displayName); setOpen(false); };
  return <div ref={ref} className="relative"><span className="mb-3 block text-lg font-semibold text-black">{label}</span><input value={value} onChange={(e) => { onChange(e.target.value); setOpen(e.target.value.trim().length >= 2); }} onKeyDown={(e) => { if (e.key === 'ArrowDown') { e.preventDefault(); setActive((active + 1) % items.length); } if (e.key === 'ArrowUp') { e.preventDefault(); setActive(active <= 0 ? items.length - 1 : active - 1); } if (e.key === 'Enter' && active >= 0) { e.preventDefault(); select(items[active]); } }} autoComplete="off" className="w-full rounded-2xl border border-gray-300 px-4 py-4 text-base outline-none focus:border-saffron" placeholder={label} />{open && <div className="absolute z-20 mt-2 w-full overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-lg">{loading ? <p className="flex items-center gap-2 px-4 py-4"><span className="h-4 w-4 animate-spin rounded-full border-2 border-saffron border-t-transparent" />Searching places...</p> : items.length ? items.map((item, i) => <button type="button" key={`${item.latitude}-${item.longitude}`} onClick={() => select(item)} className={`block w-full px-4 py-3 text-left ${i === active ? 'bg-[#fff3df]' : 'hover:bg-[#fff8ec]'}`}>{item.displayName}</button>) : <p className="px-4 py-4 text-gray-600">No places found</p>}</div>}</div>;
}

function PersonForm({ title, value, setValue }) {
  const hours = useMemo(() => Array.from({ length: 12 }, (_, i) => String(i + 1).padStart(2, '0')), []); const minutes = useMemo(() => Array.from({ length: 60 }, (_, i) => String(i).padStart(2, '0')), []);
  const update = (key, next) => setValue({ ...value, [key]: next });
  return <section className="rounded-2xl border border-[#efdfbf] bg-[#fff8ec] p-5"><h2 className="mb-5 text-2xl font-bold text-black">{title}</h2><div className="grid gap-5 md:grid-cols-2"><label><span className="mb-3 block text-lg font-semibold text-black">Name</span><input value={value.name} onChange={(e) => update('name', e.target.value)} className="w-full rounded-2xl border border-gray-300 px-4 py-4 outline-none focus:border-saffron" placeholder="Name" /></label><label><span className="mb-3 block text-lg font-semibold text-black">DOB</span><input type="date" value={value.dob} onChange={(e) => update('dob', e.target.value)} className="w-full rounded-2xl border border-gray-300 px-4 py-4 outline-none focus:border-saffron" /></label><div><span className="mb-3 block text-lg font-semibold text-black">Time</span><div className="grid grid-cols-3 gap-2">{[['hour', hours, 'HH'], ['minute', minutes, 'MM'], ['meridiem', ['AM', 'PM'], 'AM']].map(([key, options, placeholder]) => <select key={key} value={value[key]} onChange={(e) => update(key, e.target.value)} className="rounded-2xl border border-gray-300 px-3 py-4"><option value="">{placeholder}</option>{options.map((option) => <option key={option}>{option}</option>)}</select>)}</div></div><PlaceInput label="Place of Birth" value={value.place} onChange={(place) => update('place', place)} /></div></section>;
}

export default function MatchingPage({ t }) {
  const [bride, setBride] = useState(emptyPerson); const [groom, setGroom] = useState(emptyPerson); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (e) => { e.preventDefault(); setError(''); setResult(null); const person = (p) => ({ name: p.name, dob: p.dob, birthTime: `${p.meridiem === 'PM' && p.hour !== '12' ? String(Number(p.hour) + 12).padStart(2, '0') : p.meridiem === 'AM' && p.hour === '12' ? '00' : p.hour}:${p.minute}`, place: p.place }); try { setLoading(true); const { data } = await axios.post('/api/matching', { bride: person(bride), groom: person(groom) }); setResult(data.data || data); } catch (e) { setError(e.response?.data?.error || 'We could not match the Kundli. Please try again.'); } finally { setLoading(false); } };
  const guna = result?.guna_milan || result?.gunaMilan || {}; const list = guna?.guna || guna?.koota || guna?.ashtakoota || result?.ashtakoota || [];
  const score = guna.total_points ?? guna.score ?? result?.total_points; const maximum = guna.maximum_points || 36;
  return <main className="min-h-screen bg-white pb-20 pt-28"><section className="mx-auto max-w-5xl px-4 sm:px-6"><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}><Breadcrumb currentPage={t('nav.kundliMatching')} homeLabel={t('breadcrumb.home')} /><div className="rounded-[2rem] border border-[#efdfbf] bg-[linear-gradient(180deg,#fff8ec_0%,#fff1d6_100%)] p-6 sm:p-10"><h1 className="text-3xl font-bold text-black sm:text-4xl">Kundli Matching</h1><p className="mt-3 text-gray-700">Marriage compatibility through Ashtakoota matching.</p><form onSubmit={submit} className="mt-8 space-y-6"><PersonForm title="Bride Details" value={bride} setValue={setBride} /><PersonForm title="Groom Details" value={groom} setValue={setGroom} />{error && <p role="alert" className="text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-2xl bg-[#ffc400] px-8 py-4 text-xl font-semibold text-black hover:bg-[#f0b600]">{loading ? <span className="inline-flex items-center gap-3"><span className="h-5 w-5 animate-spin rounded-full border-2 border-black border-t-transparent" />Matching Kundli...</span> : 'Match Kundli'}</button></form>{result && <div className="mt-8 rounded-2xl bg-white p-6 shadow-lg"><h2 className="text-2xl font-bold text-black">Overall Compatibility</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><p><b>Compatibility %: </b>{score ? `${Math.round((score / maximum) * 100)}%` : ''}</p><p><b>Compatibility Score: </b>{score}/{maximum}</p><p><b>Recommendation: </b>{asText(result.message || guna.message)}</p></div><h3 className="mt-7 text-xl font-bold text-black">Ashtakoota</h3><div className="mt-3 overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b"><th className="p-3">Koota</th><th className="p-3">Score</th><th className="p-3">Explanation</th></tr></thead><tbody>{(Array.isArray(list) ? list : Object.entries(list).map(([name, detail]) => ({ name, ...detail }))).map((item, i) => <tr key={item.name || i} className="border-b"><td className="p-3 font-semibold">{item.name || kootas[i]}</td><td className="p-3">{item.obtained_points ?? item.points ?? item.score ?? ''}/{item.maximum_points ?? ''}</td><td className="p-3">{item.description || item.message || ''}</td></tr>)}</tbody></table></div>{Object.values(result).filter((value) => value?.description).map((value, i) => <p key={i} className="mt-4 text-gray-700">{value.description}</p>)}</div>}</div></motion.div></section></main>;
}
